# Generated by Django 3.2.15 on 2023-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('head_code', models.TextField(blank=True, null=True)),
                ('body_code', models.TextField(blank=True, null=True)),
                ('footer_code', models.TextField(blank=True, null=True)),
                ('pages', models.ManyToManyField(related_name='integrations', to='integrations.IntegrationPage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
