# Generated by Django 3.2.15 on 2022-11-21 16:19

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='cmp_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/cmpproducts'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/products'),
        ),
    ]
