# Generated by Django 3.2.15 on 2022-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marquee', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.TextField(max_length=600)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=250)),
                ('whatsapp_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
