# Generated by Django 3.2.15 on 2022-11-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cbrands'),
        ),
    ]
