# Generated by Django 3.2.15 on 2022-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20221121_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
