# Generated by Django 3.2.15 on 2023-01-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_brandcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_desc2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_keywords2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
