# Generated by Django 3.2.15 on 2023-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20230314_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
