# Generated by Django 3.2.15 on 2023-03-28 17:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_brand_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
