# Generated by Django 3.2.15 on 2022-11-17 13:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/blogs')),
                ('img_alt', models.CharField(max_length=250)),
                ('meta_desc', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created'],
            },
        ),
    ]
