# Generated by Django 3.2.15 on 2022-12-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='robots',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='schema',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
