# Generated by Django 3.2.15 on 2023-02-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_auto_20221224_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created'],
            },
        ),
    ]
